# datos_biblia.py

# lista de diccionarios, donde cada diccionario representa un libro.

libros_biblia_completo = [
    
    # Antiguo Testamento
    {"nombre": "Génesis", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 1},
    {"nombre": "Éxodo", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 2},
    {"nombre": "Levítico", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 3},
    {"nombre": "Números", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 4},
    {"nombre": "Deuteronomio", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 5},
    {"nombre": "Josué", "testamento": "Antiguo", "autor": "Josué", "tipo": "Histórico", "orden": 6},
    {"nombre": "Jueces", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Histórico", "orden": 7},
    {"nombre": "Rut", "testamento": "Antiguo", "autor": "Samuel", "tipo": "Histórico", "orden": 8},
    {"nombre": "1 Samuel", "testamento": "Antiguo", "autor": "Samuel", "tipo": "Histórico", "orden": 9},
    {"nombre": "2 Samuel", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Histórico", "orden": 10},
    {"nombre": "1 Reyes", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Histórico", "orden": 11},
    {"nombre": "2 Reyes", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Histórico", "orden": 12},
    {"nombre": "1 Crónicas", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 13},
    {"nombre": "2 Crónicas", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 14},
    {"nombre": "Esdras", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 15},
    {"nombre": "Nehemías", "testamento": "Antiguo", "autor": "Nehemías", "tipo": "Histórico", "orden": 16},
    {"nombre": "Ester", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Histórico", "orden": 17},
    {"nombre": "Job", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Poético", "orden": 18},
    {"nombre": "Salmos", "testamento": "Antiguo", "autor": "Varios", "tipo": "Poético", "orden": 19},
    {"nombre": "Proverbios", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 20},
    {"nombre": "Eclesiastés", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 21},
    {"nombre": "Cantares", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 22},
    {"nombre": "Isaías", "testamento": "Antiguo", "autor": "Isaías", "tipo": "Profético", "orden": 23},
    {"nombre": "Jeremías", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Profético", "orden": 24},
    {"nombre": "Lamentaciones", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Profético", "orden": 25},
    {"nombre": "Ezequiel", "testamento": "Antiguo", "autor": "Ezequiel", "tipo": "Profético", "orden": 26},
    {"nombre": "Daniel", "testamento": "Antiguo", "autor": "Daniel", "tipo": "Profético", "orden": 27},
    {"nombre": "Oseas", "testamento": "Antiguo", "autor": "Oseas", "tipo": "Profético", "orden": 28},
    {"nombre": "Joel", "testamento": "Antiguo", "autor": "Joel", "tipo": "Profético", "orden": 29},
    {"nombre": "Amós", "testamento": "Antiguo", "autor": "Amós", "tipo": "Profético", "orden": 30},
    {"nombre": "Abdías", "testamento": "Antiguo", "autor": "Abdías", "tipo": "Profético", "orden": 31},
    {"nombre": "Jonás", "testamento": "Antiguo", "autor": "Jonás", "tipo": "Profético", "orden": 32},
    {"nombre": "Miqueas", "testamento": "Antiguo", "autor": "Miqueas", "tipo": "Profético", "orden": 33},
    {"nombre": "Nahúm", "testamento": "Antiguo", "autor": "Nahúm", "tipo": "Profético", "orden": 34},
    {"nombre": "Habacuc", "testamento": "Antiguo", "autor": "Habacuc", "tipo": "Profético", "orden": 35},
    {"nombre": "Sofonías", "testamento": "Antiguo", "autor": "Sofonías", "tipo": "Profético", "orden": 36},
    {"nombre": "Hageo", "testamento": "Antiguo", "autor": "Hageo", "tipo": "Profético", "orden": 37},
    {"nombre": "Zacarías", "testamento": "Antiguo", "autor": "Zacarías", "tipo": "Profético", "orden": 38},
    {"nombre": "Malaquías", "testamento": "Antiguo", "autor": "Malaquías", "tipo": "Profético", "orden": 39},
    
    # Nuevo Testamento
    {"nombre": "Mateo", "testamento": "Nuevo", "autor": "Mateo", "tipo": "Evangelio", "orden": 40},
    {"nombre": "Marcos", "testamento": "Nuevo", "autor": "Marcos", "tipo": "Evangelio", "orden": 41},
    {"nombre": "Lucas", "testamento": "Nuevo", "autor": "Lucas", "tipo": "Evangelio", "orden": 42},
    {"nombre": "Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Evangelio", "orden": 43},
    {"nombre": "Hechos", "testamento": "Nuevo", "autor": "Lucas", "tipo": "Histórico", "orden": 44},
    {"nombre": "Romanos", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 45},
    {"nombre": "1 Corintios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 46},
    {"nombre": "2 Corintios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 47},
    {"nombre": "Gálatas", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 48},
    {"nombre": "Efesios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 49},
    {"nombre": "Filipenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 50},
    {"nombre": "Colosenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 51},
    {"nombre": "1 Tesalonicenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 52},
    {"nombre": "2 Tesalonicenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 53},
    {"nombre": "1 Timoteo", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 54},
    {"nombre": "2 Timoteo", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 55},
    {"nombre": "Tito", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 56},
    {"nombre": "Filemón", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 57},
    {"nombre": "Hebreos", "testamento": "Nuevo", "autor": "Anónimo", "tipo": "Epístola", "orden": 58},
    {"nombre": "Santiago", "testamento": "Nuevo", "autor": "Santiago", "tipo": "Epístola", "orden": 59},
    {"nombre": "1 Pedro", "testamento": "Nuevo", "autor": "Pedro", "tipo": "Epístola", "orden": 60},
    {"nombre": "2 Pedro", "testamento": "Nuevo", "autor": "Pedro", "tipo": "Epístola", "orden": 61},
    {"nombre": "1 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 62},
    {"nombre": "2 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 63},
    {"nombre": "3 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 64},
    {"nombre": "Judas", "testamento": "Nuevo", "autor": "Judas", "tipo": "Epístola", "orden": 65},
    {"nombre": "Apocalipsis", "testamento": "Nuevo", "autor": "Juan", "tipo": "Profético", "orden": 66},
]
