# datos.py
# Datos de autores y libros de la Biblia
datos_autores = {
    "Moisés": {"biografia": "Líder y profeta que guió a los israelitas fuera de Egipto. Recibió los Diez Mandamientos en el Monte Sinaí.","cita_famosa": "«No sólo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios.»"},
    "Pablo": {"biografia": "Originalmente un perseguidor de cristianos, se convirtió en el apóstol más influyente del cristianismo primitivo, autor de numerosas epístolas.","cita_famosa": "«Todo lo puedo en Cristo que me fortalece.»"},
    "Juan": {"biografia": "Uno de los doce apóstoles, conocido como 'el discípulo amado'. Autor de un Evangelio, tres epístolas y el Apocalipsis.","cita_famosa": "«Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito...»"},
    "Salomón": {"biografia": "Hijo del rey David, conocido por su gran sabiduría y por construir el Primer Templo de Jerusalén.","cita_famosa": "«El temor de Jehová es el principio de la sabiduría.»"},
    "Anónimo": {"biografia": "La identidad del autor es desconocida o no se atribuye con certeza.", "cita_famosa": ""},
    "Josué": {"biografia": "Sucesor de Moisés, lideró la conquista de Canaán.", "cita_famosa": "«Mi casa y yo serviremos a Jehová.»"},
    "Samuel": {"biografia": "Profeta y último juez de Israel, ungió a Saúl y a David como reyes.", "cita_famosa": "«Habla, que tu siervo oye.»"},
    "Jeremías": {"biografia": "Profeta llamado a advertir a Judá sobre la inminente destrucción por Babilonia.", "cita_famosa": "«Clama a mí, y yo te responderé.»"},
    "Esdras": {"biografia": "Sacerdote y escriba que lideró el regreso de los judíos del exilio babilónico.", "cita_famosa": "«Porque Esdras había preparado su corazón para inquirir la ley de Jehová y para cumplirla.»"},
    "Nehemías": {"biografia": "Gobernador de Judá que supervisó la reconstrucción de los muros de Jerusalén.", "cita_famosa": "«El gozo de Jehová es vuestra fortaleza.»"},
    "David": {"biografia": "Pastor, guerrero y el más grande rey de Israel. Autor de la mayoría de los Salmos.", "cita_famosa": "«Jehová es mi pastor; nada me faltará.»"},
    "Varios": {"biografia": "Este libro es una compilación de obras de múltiples autores a lo largo del tiempo.", "cita_famosa": ""},
    "Isaías": {"biografia": "Profeta del siglo VIII a.C. en el Reino de Judá, conocido por sus vastas profecías mesiánicas.", "cita_famosa": "«He aquí que la virgen concebirá, y dará a luz un hijo, y llamará su nombre Emanuel.»"},
    "Ezequiel": {"biografia": "Profeta y sacerdote que ministró a los exiliados judíos en Babilonia.", "cita_famosa": "«Os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros.»"},
    "Daniel": {"biografia": "Joven noble judío llevado al exilio en Babilonia, sirvió en la corte real y recibió visiones proféticas.", "cita_famosa": "«Mi Dios envió su ángel, el cual cerró la boca de los leones.»"},
    "Oseas": {"biografia": "Profeta del reino del norte (Israel) cuya vida personal fue un símbolo del pacto de Dios con su pueblo.", "cita_famosa": "«Y te desposaré conmigo para siempre.»"},
    "Joel": {"biografia": "Profeta de Judá, conocido por su profecía sobre el derramamiento del Espíritu Santo.", "cita_famosa": "«Derramaré mi Espíritu sobre toda carne.»"},
    "Amós": {"biografia": "Pastor de Tecoa y profeta que denunció la injusticia social en el reino del norte de Israel.", "cita_famosa": "«Pero corra el juicio como las aguas, y la justicia como impetuoso arroyo.»"},
    "Abdías": {"biografia": "Autor del libro más corto del Antiguo Testamento, profetizó contra Edom.", "cita_famosa": "«La soberbia de tu corazón te ha engañado.»"},
    "Jonás": {"biografia": "Profeta enviado a predicar arrepentimiento a la ciudad de Nínive.", "cita_famosa": "«La salvación es de Jehová.»"},
    "Miqueas": {"biografia": "Profeta contemporáneo de Isaías, conocido por su énfasis en la justicia social.", "cita_famosa": "«Hacer justicia, y amar misericordia, y humillarte ante tu Dios.»"},
    "Nahúm": {"biografia": "Profeta que anunció la caída de Nínive, la capital de Asiria.", "cita_famosa": "«Jehová es bueno, fortaleza en el día de la angustia.»"},
    "Habacuc": {"biografia": "Profeta que dialogó con Dios sobre la justicia y la soberanía divina.", "cita_famosa": "«Mas el justo por su fe vivirá.»"},
    "Sofonías": {"biografia": "Profeta que anunció el 'día del Señor' como un juicio inminente.", "cita_famosa": "«Jehová está en medio de ti, poderoso, él salvará.»"},
    "Hageo": {"biografia": "Profeta que animó a los judíos a reconstruir el Segundo Templo después del exilio.", "cita_famosa": "«Mía es la plata, y mío es el oro, dice Jehová de los ejércitos.»"},
    "Zacarías": {"biografia": "Profeta contemporáneo de Hageo, con visiones apocalípticas sobre el futuro de Israel.", "cita_famosa": "«No con ejército, ni con fuerza, sino con mi Espíritu.»"},
    "Malaquías": {"biografia": "Último profeta del Antiguo Testamento, su nombre significa 'mi mensajero'.", "cita_famosa": "«Mas a vosotros los que teméis mi nombre, nacerá el Sol de justicia.»"},
    "Mateo": {"biografia": "Recaudador de impuestos y uno de los doce apóstoles, autor del primer Evangelio.", "cita_famosa": "«Id, y haced discípulos a todas las naciones.»"},
    "Marcos": {"biografia": "Discípulo de Pedro, tradicionalmente considerado el autor del Evangelio más antiguo y conciso.", "cita_famosa": "«El tiempo se ha cumplido, y el reino de Dios se ha acercado.»"},
    "Lucas": {"biografia": "Médico y compañero de Pablo, autor del Evangelio de Lucas y el libro de los Hechos.", "cita_famosa": "«Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.»"},
    "Santiago": {"biografia": "Hermano de Jesús y líder de la iglesia en Jerusalén.", "cita_famosa": "«La fe sin obras es muerta.»"},
    "Pedro": {"biografia": "Líder de los doce apóstoles, su nombre original era Simón.", "cita_famosa": "«Mas vosotros sois linaje escogido, real sacerdocio, nación santa.»"},
    "Judas": {"biografia": "Hermano de Santiago y de Jesús, autor de una breve epístola.", "cita_famosa": "«Contendáis ardientemente por la fe que ha sido una vez dada a los santos.»"},
}

datos_libros = [
    
    # PENTATEUCO
    {"nombre": "Génesis", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 1, "cita_clave": "En el principio creó Dios los cielos y la tierra."},
    {"nombre": "Éxodo", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 2, "cita_clave": "Yo soy el SEÑOR tu Dios, que te saqué de la tierra de Egipto, de casa de servidumbre."},
    {"nombre": "Levítico", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 3, "cita_clave": "Seréis santos, porque yo, el SEÑOR vuestro Dios, soy santo."},
    {"nombre": "Números", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 4, "cita_clave": "El SEÑOR te bendiga, y te guarde; el SEÑOR haga resplandecer su rostro sobre ti."},
    {"nombre": "Deuteronomio", "testamento": "Antiguo", "autor": "Moisés", "tipo": "Pentateuco", "orden": 5, "cita_clave": "Oye, Israel: El SEÑOR nuestro Dios, el SEÑOR uno es."},
    
    # HISTÓRICOS (AT)
    {"nombre": "Josué", "testamento": "Antiguo", "autor": "Josué", "tipo": "Histórico", "orden": 6, "cita_clave": "Esfuérzate y sé valiente; porque tú repartirás a este pueblo por heredad la tierra."},
    {"nombre": "Jueces", "testamento": "Antiguo", "autor": "Samuel", "tipo": "Histórico", "orden": 7, "cita_clave": "En aquellos días no había rey en Israel; cada uno hacía lo que bien le parecía."},
    {"nombre": "Rut", "testamento": "Antiguo", "autor": "Samuel", "tipo": "Histórico", "orden": 8, "cita_clave": "No me ruegues que te deje... a dondequiera que tú fueres, iré yo."},
    {"nombre": "1 Samuel", "testamento": "Antiguo", "autor": "Samuel", "tipo": "Histórico", "orden": 9, "cita_clave": "El hombre mira lo que está delante de sus ojos, pero Jehová mira el corazón."},
    {"nombre": "2 Samuel", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Histórico", "orden": 10, "cita_clave": "Tu casa y tu reino serán firmes para siempre delante de tu rostro."},
    {"nombre": "1 Reyes", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Histórico", "orden": 11, "cita_clave": "Pide lo que quieras que yo te dé."},
    {"nombre": "2 Reyes", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Histórico", "orden": 12, "cita_clave": "He aquí, si yo soy varón de Dios, descienda fuego del cielo, y consúmate con tus cincuenta."},
    {"nombre": "1 Crónicas", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 13, "cita_clave": "¡Oh, si me dieras bendición, y ensancharas mi territorio!"},
    {"nombre": "2 Crónicas", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 14, "cita_clave": "Si se humillare mi pueblo, sobre el cual mi nombre es invocado... yo oiré desde los cielos."},
    {"nombre": "Esdras", "testamento": "Antiguo", "autor": "Esdras", "tipo": "Histórico", "orden": 15, "cita_clave": "Porque la buena mano de su Dios estaba sobre él."},
    {"nombre": "Nehemías", "testamento": "Antiguo", "autor": "Nehemías", "tipo": "Histórico", "orden": 16, "cita_clave": "El Dios de los cielos, él nos prosperará, y nosotros sus siervos nos levantaremos y edificaremos."},
    {"nombre": "Ester", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Histórico", "orden": 17, "cita_clave": "¿Y quién sabe si para esta hora has llegado al reino?"},
    
    # POÉTICOS
    {"nombre": "Job", "testamento": "Antiguo", "autor": "Anónimo", "tipo": "Poético", "orden": 18, "cita_clave": "Yo sé que mi Redentor vive."},
    {"nombre": "Salmos", "testamento": "Antiguo", "autor": "David", "tipo": "Poético", "orden": 19, "cita_clave": "Jehová es mi pastor; nada me faltará."},
    {"nombre": "Proverbios", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 20, "cita_clave": "El temor de Jehová es el principio de la sabiduría."},
    {"nombre": "Eclesiastés", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 21, "cita_clave": "Vanidad de vanidades, dijo el Predicador; vanidad de vanidades, todo es vanidad."},
    {"nombre": "Cantares", "testamento": "Antiguo", "autor": "Salomón", "tipo": "Poético", "orden": 22, "cita_clave": "Las muchas aguas no podrán apagar el amor, ni lo ahogarán los ríos."},
    
    # PROFÉTICOS (AT)
    {"nombre": "Isaías", "testamento": "Antiguo", "autor": "Isaías", "tipo": "Profético", "orden": 23, "cita_clave": "Porque un niño nos es nacido, hijo nos es dado, y el principado sobre su hombro."},
    {"nombre": "Jeremías", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Profético", "orden": 24, "cita_clave": "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz."},
    {"nombre": "Lamentaciones", "testamento": "Antiguo", "autor": "Jeremías", "tipo": "Profético", "orden": 25, "cita_clave": "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias."},
    {"nombre": "Ezequiel", "testamento": "Antiguo", "autor": "Ezequiel", "tipo": "Profético", "orden": 26, "cita_clave": "Os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros."},
    {"nombre": "Daniel", "testamento": "Antiguo", "autor": "Daniel", "tipo": "Profético", "orden": 27, "cita_clave": "El Dios del cielo levantará un reino que no será jamás destruido."},
    {"nombre": "Oseas", "testamento": "Antiguo", "autor": "Oseas", "tipo": "Profético", "orden": 28, "cita_clave": "Mi pueblo fue destruido, porque le faltó conocimiento."},
    {"nombre": "Joel", "testamento": "Antiguo", "autor": "Joel", "tipo": "Profético", "orden": 29, "cita_clave": "Y después de esto derramaré mi Espíritu sobre toda carne."},
    {"nombre": "Amós", "testamento": "Antiguo", "autor": "Amós", "tipo": "Profético", "orden": 30, "cita_clave": "Pero corra el juicio como las aguas, y la justicia como impetuoso arroyo."},
    {"nombre": "Abdías", "testamento": "Antiguo", "autor": "Abdías", "tipo": "Profético", "orden": 31, "cita_clave": "La soberbia de tu corazón te ha engañado."},
    {"nombre": "Jonás", "testamento": "Antiguo", "autor": "Jonás", "tipo": "Profético", "orden": 32, "cita_clave": "La salvación es de Jehová."},
    {"nombre": "Miqueas", "testamento": "Antiguo", "autor": "Miqueas", "tipo": "Profético", "orden": 33, "cita_clave": "Oh hombre, él te ha declarado lo que es bueno... solamente hacer justicia, y amar misericordia."},
    {"nombre": "Nahúm", "testamento": "Antiguo", "autor": "Nahúm", "tipo": "Profético", "orden": 34, "cita_clave": "Jehová es bueno, fortaleza en el día de la angustia."},
    {"nombre": "Habacuc", "testamento": "Antiguo", "autor": "Habacuc", "tipo": "Profético", "orden": 35, "cita_clave": "Mas el justo por su fe vivirá."},
    {"nombre": "Sofonías", "testamento": "Antiguo", "autor": "Sofonías", "tipo": "Profético", "orden": 36, "cita_clave": "Jehová está en medio de ti, poderoso, él salvará."},
    {"nombre": "Hageo", "testamento": "Antiguo", "autor": "Hageo", "tipo": "Profético", "orden": 37, "cita_clave": "Mía es la plata, y mío es el oro, dice Jehová de los ejércitos."},
    {"nombre": "Zacarías", "testamento": "Antiguo", "autor": "Zacarías", "tipo": "Profético", "orden": 38, "cita_clave": "No con ejército, ni con fuerza, sino con mi Espíritu, ha dicho Jehová de los ejércitos."},
    {"nombre": "Malaquías", "testamento": "Antiguo", "autor": "Malaquías", "tipo": "Profético", "orden": 39, "cita_clave": "Mas a vosotros los que teméis mi nombre, nacerá el Sol de justicia."},
    
    # EVANGELIOS
    {"nombre": "Mateo", "testamento": "Nuevo", "autor": "Mateo", "tipo": "Evangelio", "orden": 40, "cita_clave": "Yendo, predicad, diciendo: El reino de los cielos se ha acercado."},
    {"nombre": "Marcos", "testamento": "Nuevo", "autor": "Marcos", "tipo": "Evangelio", "orden": 41, "cita_clave": "El tiempo se ha cumplido, y el reino de Dios se ha acercado; arrepentíos, y creed en el evangelio."},
    {"nombre": "Lucas", "testamento": "Nuevo", "autor": "Lucas", "tipo": "Evangelio", "orden": 42, "cita_clave": "Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido."},
    {"nombre": "Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Evangelio", "orden": 43, "cita_clave": "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí."},
    
    # HISTÓRICO (NT)
    {"nombre": "Hechos", "testamento": "Nuevo", "autor": "Lucas", "tipo": "Histórico", "orden": 44, "cita_clave": "Pero recibiréis poder, cuando haya venido sobre vosotros el Espíritu Santo."},
    
    # EPÍSTOLAS 
    {"nombre": "Romanos", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 45, "cita_clave": "Porque no me avergüenzo del evangelio, porque es poder de Dios para salvación a todo aquel que cree."},
    {"nombre": "1 Corintios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 46, "cita_clave": "Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor."},
    {"nombre": "2 Corintios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 47, "cita_clave": "Bástate mi gracia; porque mi poder se perfecciona en la debilidad."},
    {"nombre": "Gálatas", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 48, "cita_clave": "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe."},
    {"nombre": "Efesios", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 49, "cita_clave": "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios."},
    {"nombre": "Filipenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 50, "cita_clave": "Todo lo puedo en Cristo que me fortalece."},
    {"nombre": "Colosenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 51, "cita_clave": "Y todo lo que hacéis, sea de palabra o de hecho, hacedlo todo en el nombre del Señor Jesús."},
    {"nombre": "1 Tesalonicenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 52, "cita_clave": "Estad siempre gozosos. Orad sin cesar. Dad gracias en todo."},
    {"nombre": "2 Tesalonicenses", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 53, "cita_clave": "Si alguno no quiere trabajar, tampoco coma."},
    {"nombre": "1 Timoteo", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 54, "cita_clave": "Porque raíz de todos los males es el amor al dinero."},
    {"nombre": "2 Timoteo", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 55, "cita_clave": "Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir."},
    {"nombre": "Tito", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 56, "cita_clave": "Nos salvó, no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia."},
    {"nombre": "Filemón", "testamento": "Nuevo", "autor": "Pablo", "tipo": "Epístola", "orden": 57, "cita_clave": "Para que la participación de tu fe sea eficaz en el conocimiento de todo el bien que está en vosotros por Cristo Jesús."},
    {"nombre": "Hebreos", "testamento": "Nuevo", "autor": "Anónimo", "tipo": "Epístola", "orden": 58, "cita_clave": "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve."},
    {"nombre": "Santiago", "testamento": "Nuevo", "autor": "Santiago", "tipo": "Epístola", "orden": 59, "cita_clave": "Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos."},
    {"nombre": "1 Pedro", "testamento": "Nuevo", "autor": "Pedro", "tipo": "Epístola", "orden": 60, "cita_clave": "Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios."},
    {"nombre": "2 Pedro", "testamento": "Nuevo", "autor": "Pedro", "tipo": "Epístola", "orden": 61, "cita_clave": "El Señor no retarda su promesa, según algunos la tienen por tardanza, sino que es paciente para con nosotros."},
    {"nombre": "1 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 62, "cita_clave": "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados."},
    {"nombre": "2 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 63, "cita_clave": "Y este es el amor, que andemos según sus mandamientos."},
    {"nombre": "3 Juan", "testamento": "Nuevo", "autor": "Juan", "tipo": "Epístola", "orden": 64, "cita_clave": "No tengo yo mayor gozo que este, el oír que mis hijos andan en la verdad."},
    {"nombre": "Judas", "testamento": "Nuevo", "autor": "Judas", "tipo": "Epístola", "orden": 65, "cita_clave": "A aquel que es poderoso para guardaros sin caída, y presentaros sin mancha."},
    
    # PROFÉTICO (NT)
    {"nombre": "Apocalipsis", "testamento": "Nuevo", "autor": "Juan", "tipo": "Profético", "orden": 66, "cita_clave": "He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él."},
]